# Generated by Django 4.0.4 on 2022-07-11 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affi_img', models.ImageField(null=True, upload_to='file')),
                ('affi_name', models.ImageField(null=True, upload_to='file')),
            ],
        ),
        migrations.CreateModel(
            name='associate_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asm_name', models.CharField(max_length=20)),
                ('asm_phno', models.CharField(max_length=15)),
                ('asm_email', models.EmailField(max_length=254)),
                ('asm_position', models.CharField(max_length=20)),
                ('asm_image', models.ImageField(null=True, upload_to='image/associates')),
            ],
        ),
        migrations.CreateModel(
            name='galleryfolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder_name', models.CharField(max_length=25)),
                ('folder_image_url', models.ImageField(null=True, upload_to='gallery/')),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.ImageField(null=True, upload_to='gallery/')),
                ('folder_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karateApp.galleryfolder')),
            ],
        ),
    ]
