# Generated by Django 4.0.4 on 2022-07-11 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associate_members',
            name='asm_name',
            field=models.CharField(max_length=30),
        ),
    ]
