# Generated by Django 4.1 on 2022-08-15 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='videos',
        ),
    ]
