# Generated by Django 4.1 on 2022-08-15 04:26

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0005_delete_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kata_name', models.CharField(max_length=50)),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
    ]
