# Generated by Django 4.1 on 2022-08-15 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0006_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='event_gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_image_url', models.ImageField(null=True, upload_to='gallery/')),
                ('events_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karateApp.news')),
            ],
        ),
    ]
