# Generated by Django 4.1 on 2022-08-15 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0007_event_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regform', models.ImageField(null=True, upload_to='gallery/')),
                ('eventsform_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karateApp.news')),
            ],
        ),
    ]
