# Generated by Django 4.1 on 2022-09-06 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0008_registerform'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=25)),
                ('usub', models.CharField(max_length=60)),
                ('msgs', models.TextField()),
            ],
        ),
    ]
