# Generated by Django 4.1 on 2022-09-06 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0009_usermessages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=60)),
                ('contents', models.TextField()),
                ('eventnews_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='karateApp.news')),
            ],
        ),
    ]
