# Generated by Django 4.1 on 2022-09-07 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0010_event_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admincontent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headname', models.CharField(max_length=25)),
                ('contparagraph', models.TextField()),
                ('contimg', models.ImageField(null=True, upload_to='gallery/')),
            ],
        ),
    ]
