# Generated by Django 4.1 on 2022-09-09 09:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0014_graduations'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='uemail',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usermessages',
            name='uphone',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
