# Generated by Django 4.1 on 2022-09-12 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('karateApp', '0015_usermessages_uemail_usermessages_uphone'),
    ]

    operations = [
        migrations.AddField(
            model_name='associate_members',
            name='asm_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='associate_members',
            name='asm_position',
            field=models.CharField(max_length=150),
        ),
    ]
